### ISSUE TITLE
Fix pi-slideshow user's bash profile on hightower

### ISSUE THREAD

**Issue by tylerecouture** [timberline-secondary/hackerspace-scripts-2#117]
There's no bash environment for some reason.  No history (up arrow) no auto completion, no styling in the terminal, for pi-slideshow user on hightower server

**Comment by punctuations** [comment]
Just fixed this, it was a lot more simple of a fix than I had originally thought, I just had to run (from a sudoer account) `sudo chsh -s /bin/bash pi-slideshow`

I was able to do this because I echoed the output of $SHELL and it was set to /bin/sh rather than /bin/bash
