### ISSUE TITLE
Doesn't ask to regen slideshow after adding media to collection

### ISSUE THREAD

**Issue by tylerecouture** [timberline-secondary/hackerspace-scripts-2#122]
Should use same behavior as the other add media (ask to regen after adding)

**Comment by punctuations** [comment]
It should behave the same, no?

The way that the collections script works is by calling the add_media function used in add media.

(code here https://github.com/timberline-secondary/hackerspace-scripts-2/blob/master/scripts/TVs/collection_add_media.py#L29)

**Comment by tylerecouture** [comment]
Let me double check it.

**Comment by punctuations** [comment]
What's the status on this? @tylerecouture

**Comment by tylerecouture** [comment]
I don't remember. Gonna close.

**Comment by punctuations** [comment]
duplicate of latest stuff in #111 ?
