### ISSUE TITLE
Create a test suite for this

### ISSUE THREAD

**Issue by tylerecouture** [timberline-secondary/hackerspace-scripts-2#126]
https://realpython.com/python-testing/

Use built in unittest probably easiest.

For this issue, just create it and make it runnable inside docker. Thank we can set up automated testing GitHub Action and actually write tests in other issues.

**Comment by punctuations** [comment]
what kind of tests would be run? Most of this system is kind of hard to test for considering it has to interface with lots of external stuff

**Comment by tylerecouture** [comment]
Start with unit tests: that given input values to a function result in the expected output values.
