### ISSUE TITLE
How to remove media from a collection?

### ISSUE THREAD

**Issue by tylerecouture** [timberline-secondary/hackerspace-scripts-2#127]
It doesn't seem to work:

![image](https://user-images.githubusercontent.com/10604391/205752535-24355e58-3700-46c1-9d4b-2948b60bfa24.png)

Might need its own "collection_view_or_remove_media" script.

**Comment by punctuations** [comment]
Could this be case-sensitive?

**Comment by tylerecouture** [comment]
You are correct, however they are not listed:

![image](https://user-images.githubusercontent.com/10604391/206765265-32aefac8-d14c-4fe5-b9b7-d933cab8b1e0.png)
