### ISSUE TITLE
Gif to mp4 videos break player

### ISSUE THREAD

**Issue by tylerecouture** [timberline-secondary/hackerspace-scripts-2#128]
Whatever is being output from the gif to video script is breaking the video player.  Does it use ffmpeg or something else?

Here's an example that breaks the video player when converted to mp4:
https://d10ge8y4vx8iud.cloudfront.net/public_media/portfolios/video/2022/11/sunset.gif

Test using the underlying video player, omxplayer locally before PRing your fix.  Or to debug, you can view logs on a pi-tv:

![image](https://user-images.githubusercontent.com/10604391/205756852-466cce33-f7d4-4c62-a867-7d8cd795f00a.png)

**Comment by punctuations** [comment]
It seems the example you linked is ~2 frames long, therefore it would have to be using ffmpeg specifically this: [`02dd8e6` (#121)](https://github.com/timberline-secondary/hackerspace-scripts-2/pull/121/commits/02dd8e631eebd837d1d7254cb80d3a843cbe780a#diff-c82eca1819d9bdef1a76518d6e572aaaceffaa7f1e024046a48c1573177abe96R161) (the command given here: https://github.com/timberline-secondary/hackerspace-scripts-2/issues/47#issue-1289288838)

**Comment by tylerecouture** [comment]
Ok.  Well we know the pictures to mp4 videos work, can you look to see if there is any difference?  Do they both use the same encoding etc? The gif to vid command is using yuv240p, I think that's different?

**Comment by punctuations** [comment]
What's the picture to mp4 video stuff?

**Comment by tylerecouture** [comment]
The slideshow generator. Refresh video? It takes all the uploaded picture
media (PNG and jpg) and generates an MP4 from them

**Comment by punctuations** [comment]
I've ran the converted gif on the raspberry pi TV, however that does not seem to be an issue with it, it displays fine. Here is a screenshot of the crashed log of tv3:
<img width="961" alt="image" src="https://user-images.githubusercontent.com/37005919/206533205-acdcf32d-d529-4815-a1ea-818e2d32df66.png">

**Comment by tylerecouture** [comment]
Ok, I'll leave it to you if you want to try to troubleshoot that, or generate the gif>mp4 using a different process.

**Comment by punctuations** [comment]
for a progress update, it has been almost solved, I am using moviepy to make the gif conversion better; however, on short gifs (I assume <1s [i.e. <~5 frames]) they stutter in the middle for some reason where it freezes on just 1 frame for a little bit
