### ISSUE TITLE
Add new media breaks after regenerating slideshow

### ISSUE THREAD

**Issue by tylerecouture** [timberline-secondary/hackerspace-scripts-2#132]
![image](https://user-images.githubusercontent.com/10604391/207167174-e1ba5048-0efc-43d0-90fe-d8371a44c112.png)

**Comment by punctuations** [comment]
What happened? Was a media url entered afterward? I'm confused

**Comment by tylerecouture** [comment]
Let me re-check after your other PR on this.

**Comment by punctuations** [comment]
does #130 fix this issue?
