### ISSUE TITLE
Error when restarting pi-themes

### ISSUE THREAD

**Issue by tylerecouture** [timberline-secondary/hackerspace-scripts-2#135]
Check out the tv-pi reset code works, those don't crash when restarting (maybe it needs a shutdown -r instead of reboot... if that's what it's doing?)

![image](https://user-images.githubusercontent.com/10604391/207440982-6fbd6e30-46f2-4c61-969b-30bd4c0dcb16.png)

**Comment by punctuations** [comment]
This is a weird error, is this reproducible? I am lost on how and where it would terminate the connection before sending the command considering the code for this is so simple. (for ref: https://github.com/timberline-secondary/hackerspace-scripts-2/blob/master/scripts/_utils/pi.py#L19)

**Comment by punctuations** [comment]
And to address the code it does currently call ` shutdown -r `

Possibly this error could be due to the connection originally working but then possibly the pi temporarily lost Internet connection, if it took a while print that error message that could be a contender, otherwise I haven't a clue

**Comment by tylerecouture** [comment]
Can you try it a few times in the morning and see if you can get it to happen.  If not I'll close it.

**Comment by punctuations** [comment]
I just ran it and it reboot without error

**Comment by tylerecouture** [comment]
Once? Try 5 times.

**Comment by punctuations** [comment]
I tried back to back to back and it worked every time
