### ISSUE TITLE
Lab report lies

### ISSUE THREAD

**Issue by tylerecouture** [timberline-secondary/hackerspace-scripts-2#136]
"All" does not work, despite instructions...

![image](https://user-images.githubusercontent.com/10604391/207932494-fdac547f-dba6-4d03-8b5d-2254bf32030e.png)

**Comment by punctuations** [comment]
While compartmentalizing the method that creates this prompt it lost the following code:

(I will re-add this, my bad)

```python
     if num_list == "":
        return

    if num_list[0] == "all":
        num_list = [f"{i}" for i in range(0, 32)]  # list of strings.  0 will cause problem if int instead of str
```
