### ISSUE TITLE
VIEW OR REMOVE MEDIA bug

### ISSUE THREAD

**Issue by tylerecouture** [timberline-secondary/hackerspace-scripts-2#145]
Tried to view the one listed file (title image) and threw an error:
![image](https://user-images.githubusercontent.com/10604391/211107566-0b42fcbb-6dbd-4a60-81b3-58ab6f965028.png)

**Comment by tylerecouture** [comment]
Confirmed the file exists, but the script is not looking in the correct location.  It's looking in root of tv2 instead of in the directory that has images (the username directory)

**Comment by punctuations** [comment]
I'm surprised this has gone undetected for so long, the issue is to do with L#63 in `view_or_remove_media.py`, the merge point was offset incorrectly by 1! I'll be pushing a fix very shortly
