### ISSUE TITLE
bad transparency mask error

### ISSUE THREAD

**Issue by tylerecouture** [timberline-secondary/hackerspace-scripts-2#146]
When uploading this image:
https://d10ge8y4vx8iud.cloudfront.net/public_media/portfolios/video/2019/02/pikachu2.png

![image](https://user-images.githubusercontent.com/10604391/211108368-329b0751-b2c1-4c6b-898c-a95b921fe2d8.png)

**Comment by punctuations** [comment]
I wish gifs never existed

**Comment by tylerecouture** [comment]
This is a normal png

**Comment by punctuations** [comment]
I will find a better method to convert transparency
