### ISSUE TITLE
Collection of test media

### ISSUE THREAD

**Issue by tylerecouture** [timberline-secondary/hackerspace-scripts-2#147]
Add them to a directory in this repo, then make sure you test all of them before making a PR.  Animated gifs, static gifs, pngs with and without transparency, etc

**Comment by tylerecouture** [comment]
That way we can just drag and drop them from github or local repo into the control panel's add media script to test that any code changes haven't broken things

**Comment by punctuations** [comment]
wouldn't this be solved when unit tests are implemented?

**Comment by tylerecouture** [comment]
It might be, but unit tests are a dream, so that we don't break the control panel with future additions.  Priority is getting the control panel working now, and we can't know that unless we have files to actually, manually, laboriously, testing it with using the test student.
