### ISSUE TITLE
New command: Crashed TV Pi logs

### ISSUE THREAD

**Issue by tylerecouture** [timberline-secondary/hackerspace-scripts-2#158]
Instead of worrying about video, a new command to just report why a TV Pi player crashed so we can remove the file.

`systemctl status omxplayer` or whatever we've been using to see the last few lines of the logs on a crashed pi

**Comment by punctuations** [comment]
will this be like the lab_report command but for TVs and to get their processes?

**Comment by tylerecouture** [comment]
It can be simpler than that cus it's obvious which TV pi has crashes. Ask for the tv# and just do that one.
