### ISSUE TITLE
Media integrity, or check media types

### ISSUE THREAD

**Issue by tylerecouture** [timberline-secondary/hackerspace-scripts-2#46]
https://github.com/timberline-secondary/hackerspace-todo/issues/54

Check integrity of media files (to prevent moviemaker script from breaking, I can provide examples that I know break it)

pngs exported from piskel will not work for some reason, break ffmpeg when trying to generate the slideshow mp4

mp4s generated from ezgif.com (convert gif to mp4) don't work either.

Try to figure out what it is about these files and reject them if detected.

**Comment by punctuations** [comment]
is this a control-panel command to be added or to be fixed?

**Comment by punctuations** [comment]
closed in #48
