### ISSUE TITLE
add_media script should accept gifs

### ISSUE THREAD

**Issue by tylerecouture** [timberline-secondary/hackerspace-scripts-2#47]
1.  Check for non-animated gif and convert to png (using PIL/pillow? I think already installed via pip for another script) - Black background (no transparency)
2. Check for animated gif and convert to mp4 (with ffmpeg or a python library?), add option to loop a certain number of times (ask user for number, default to 4)
https://unix.stackexchange.com/questions/40638/how-to-do-i-convert-an-animated-gif-to-an-mp4-or-mv4-on-the-command-line

`ffmpeg -stream_loop 4 -i normal.gif loop.gif -y;ffmpeg -i loop.gif -pix_fmt yuv420p -vf "scale=trunc(iw/2)*2:trunc(ih/2)*2" loop.mp4`

**Comment by punctuations** [comment]
extension of https://github.com/timberline-secondary/hackerspace-scripts-2/issues/46 ?

**Comment by punctuations** [comment]
closed as per #48

**Comment by tylerecouture** [comment]
Can't verify, broken.

**Comment by tylerecouture** [comment]
@punctuations Doesn't work.  Do you test your code? Not automated/unit testing, but just test to even see if it works?

![image](https://user-images.githubusercontent.com/10604391/194409082-d5cec2ba-e0aa-4396-a9be-ff9df286cd3f.png)
