### ISSUE TITLE
Don't break when bad url is provded

### ISSUE THREAD

**Issue by tylerecouture** [timberline-secondary/hackerspace-scripts-2#49]
Adding a new theme and pasting the wrong thing and the control panel bails.

Instead: Catch the exception, provide feedback (bad url) and try again:
![image](https://user-images.githubusercontent.com/10604391/192380960-365322d6-4a54-42e2-8f4f-d1d3e6950502.png)

**Comment by punctuations** [comment]
ok will fix today
