### ISSUE TITLE
Broken User Management functions

### ISSUE THREAD

**Issue by tylerecouture** [timberline-secondary/hackerspace-scripts-2#53]
Some of the user management functions got broke. Note sure what happened as they used to work.

These two are broken for sure, maybe others:

User Management > Repair User Desktop
User Management > Refresh User

![image](https://user-images.githubusercontent.com/10604391/194368163-e6ad406b-15d5-4ce4-9493-4cd752e8ad81.png)

**Comment by punctuations** [comment]
This seems to be an issue with python's `getpass` builtin library
