### ISSUE TITLE
add_media script should accept svg

### ISSUE THREAD

**Issue by tylerecouture** [timberline-secondary/hackerspace-scripts-2#57]
Can use command line inkscape to export to a png with black background.

See `add_new_title.py` for a script that does this already for the title slides (though it doesn't set the background which you might need to do)

**Comment by tylerecouture** [comment]
@punctuations the PR provided doesn't set a black background.

**Comment by tylerecouture** [comment]
@punctuations is this completed now?

**Comment by punctuations** [comment]
Yes

**Comment by punctuations** [comment]
The PR that fixed this is mentioned above ^

**Comment by tylerecouture** [comment]
@punctuations 
![image](https://github.com/timberline-secondary/hackerspace-scripts-2/assets/10604391/88e1183a-9649-49a1-a65a-e3a9adaf0a94)

**Comment by tylerecouture** [comment]
@punctuations This is when trying to add an svg to a collection.
