### ISSUE TITLE
Grade 9 mode tweaks

### ISSUE THREAD

**Issue by tylerecouture** [timberline-secondary/hackerspace-scripts-2#80]
- [ ] ~~lower case e but capital D is triggering me.  Make both lowercase~~
- [ ] Provide feedback "Muting Entrance Theme Machine...." and "Turning off TVs 1-3"
- [ ] Don't turn off TV 4 (outside the classroom)

![image](https://user-images.githubusercontent.com/10604391/196526886-4437ec22-6b4a-4bca-8376-51aa28f5ba2d.png)

**Comment by punctuations** [comment]
The lowercase e and capital D is for default and non-default

**Comment by tylerecouture** [comment]
That's fair.
