### ISSUE TITLE
motd bug

### ISSUE THREAD

**Issue by tylerecouture** [timberline-secondary/hackerspace-scripts-2#91]
![image](https://user-images.githubusercontent.com/10604391/200690559-99941652-400c-4fac-9a5e-c508b4706515.png)

**Comment by punctuations** [comment]
found why the issue occurs: https://stackoverflow.com/questions/24777597/value-too-great-for-base-error-token-is-08

**Comment by punctuations** [comment]
added a fix as per [#5 in hackerspace-control-repo](https://github.com/timberline-secondary/hackerspace-control-repo/pull/5)
